<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression &amp; Interpretability Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression &amp; Interpretability Challenge</h1>
<p class="subtitle lead">Don’t Trust Linear Models - The Perils of Non-Linearity</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="interrogating-linear-regression-with-non-linear-proxies" class="level1">
<h1>Interrogating Linear Regression with Non-Linear Proxies</h1>
<p>Researchers often treat monotonic proxies as “close enough” to the causal variable. This walkthrough recreates a stress–anxiety scenario to show how that shortcut breaks regression interpretability. Each question below matches the challenge rubric, pairing code-generated evidence with plain-language interpretation.</p>
<section id="data-and-proxy-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="data-and-proxy-diagnostics">Data and Proxy Diagnostics</h2>
<div class="cell" data-execution_count="2">
<div id="tbl-observations" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Observed data with known true relationships
</figcaption>
<div aria-describedby="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Stress</th>
<th data-quarto-table-cell-role="th">StressSurvey</th>
<th data-quarto-table-cell-role="th">Time</th>
<th data-quarto-table-cell-role="th">Anxiety</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0</td>
<td>0</td>
<td>0.0</td>
<td>0.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>8</td>
<td>9</td>
<td>2.1</td>
<td>8.21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<div id="cell-fig-stress-proxy" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-stress-proxy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stress-proxy-output-1.png" width="758" height="470" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: StressSurvey is monotonic but not linear in true stress
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="analysis-and-answers" class="level2">
<h2 class="anchored" data-anchor-id="analysis-and-answers">Analysis and Answers</h2>
<section id="question-1-bivariate-regression-with-stresssurvey" class="level3">
<h3 class="anchored" data-anchor-id="question-1-bivariate-regression-with-stresssurvey">Question 1: Bivariate Regression with StressSurvey</h3>
<div id="reg1-stresssurvey" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
Question 1: Bivariate Regression - Anxiety ~ StressSurvey
======================================================================
|              |   Estimate |   Std. Error |      t |    p-value |   95% CI Low |   95% CI High |
|:-------------|-----------:|-------------:|-------:|-----------:|-------------:|--------------:|
| Intercept    |     -1.524 |      nan     | nan    | nan        |       -3.051 |         0.003 |
| StressSurvey |      1.047 |        0.096 |  10.88 |   6.68e-08 |        0.839 |         1.255 |
| const        |    nan     |        0.707 |  -2.16 |   0.0504   |      nan     |       nan     |

R-squared: 0.901</code></pre>
</div>
</div>
<p>The estimated regression line is</p>
<p><span class="math display">\[\widehat{Anxiety} = -1.524 + 1.047 \times StressSurvey.\]</span></p>
<p>For beginners, read this as: start at −1.524 when the survey reports zero stress, and then add about 1.05 anxiety points for every one-unit bump on the survey scale. The healthy part of the story is the <span class="math inline">\(R^2\)</span> of 0.901, which says the line hugs the data closely. The worrying part is that the survey tries to stand in for real cortisol, and it stretches more aggressively at higher stress levels. The regression compensates by pushing the slope above 1 and by dropping the intercept below zero. So the equation “fits” but quietly distorts the true cause-and-effect relationship.</p>
</section>
<section id="question-2-visualization-of-bivariate-relationship-stresssurvey" class="level3">
<h3 class="anchored" data-anchor-id="question-2-visualization-of-bivariate-relationship-stresssurvey">Question 2: Visualization of Bivariate Relationship – StressSurvey</h3>
<div id="cell-fig-stresssurvey-anxiety" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="fig-stresssurvey-anxiety" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stresssurvey-anxiety-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stresssurvey-anxiety-output-1.png" width="758" height="469" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stresssurvey-anxiety-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: StressSurvey vs Anxiety with fitted line
</figcaption>
</figure>
</div>
</div>
</div>
<p>The dots show Anxiety (vertical axis) for each survey response (horizontal axis). Notice the horizontal “steps”: the survey records three different anxiety outcomes for every real stress level. The final step from 9 to 12 shoots upward more sharply than earlier steps. The red line averages across those steps, so it floats above the low-stress points and sinks below the high-stress ones. This picture is the geometric version of the warning above—our proxy is monotonic, yet the violation of straight-line growth silently bends the fitted slope.</p>
</section>
<section id="question-3-bivariate-regression-with-time" class="level3">
<h3 class="anchored" data-anchor-id="question-3-bivariate-regression-with-time">Question 3: Bivariate Regression with Time</h3>
<div id="reg3-time" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
Question 3: Bivariate Regression - Anxiety ~ Time
======================================================================
|           |   Estimate |   Std. Error |      t |   p-value |   95% CI Low |   95% CI High |
|:----------|-----------:|-------------:|-------:|----------:|-------------:|--------------:|
| Intercept |     -3.68  |      nan     | nan    | nan       |       -8.504 |         1.144 |
| Time      |      5.341 |        1.305 |   4.09 |   0.00127 |        2.522 |         8.16  |
| const     |    nan     |        2.233 |  -1.65 |   0.123   |      nan     |       nan     |

R-squared: 0.563</code></pre>
</div>
</div>
<p>Regressing Anxiety on Time produces</p>
<p><span class="math display">\[\widehat{Anxiety} = -3.680 + 5.341 \times Time,\]</span></p>
<p>with <span class="math inline">\(R^2 = 0.563\)</span>. Interpreted literally, the model says “start at −3.68 anxiety points and add 5.34 points for each extra hour online.” That story is implausible (negative anxiety at zero time!) and it clashes with the true 0.1 coefficient we built into the data. The culprit is omitted-variable bias: Stress is missing from this regression, so the model stuffs stress-driven variation into the Time coefficient and inflates it more than fifty-fold.</p>
</section>
<section id="question-4-visualization-of-bivariate-relationship-time" class="level3">
<h3 class="anchored" data-anchor-id="question-4-visualization-of-bivariate-relationship-time">Question 4: Visualization of Bivariate Relationship – Time</h3>
<div id="cell-fig-time-anxiety" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div id="fig-time-anxiety" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-time-anxiety-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-time-anxiety-output-1.png" width="758" height="469" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-time-anxiety-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Time vs Anxiety with fitted line
</figcaption>
</figure>
</div>
</div>
</div>
<p>Each dot still plots Time (horizontal) versus Anxiety (vertical), but the dots now form tall columns instead of a tidy upward march. That “vertical” pattern means anxiety differs wildly even when Time stays fixed—because those students are sitting at different stress levels. The regression line, oblivious to stress, leans steeply upward and claims social media is the hero or villain. Visually, you can see why the coefficient exaggerates the effect: the model chases vertical variation it cannot explain.</p>
</section>
<section id="question-5-multiple-regression-with-stresssurvey-and-time" class="level3">
<h3 class="anchored" data-anchor-id="question-5-multiple-regression-with-stresssurvey-and-time">Question 5: Multiple Regression with StressSurvey and Time</h3>
<div id="reg5-multiple-stresssurvey" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
Question 5: Multiple Regression - Anxiety ~ StressSurvey + Time
======================================================================
|              |   Estimate |   Std. Error |      t |    p-value |   95% CI Low |   95% CI High |
|:-------------|-----------:|-------------:|-------:|-----------:|-------------:|--------------:|
| Intercept    |      0.589 |      nan     | nan    | nan        |       -1.664 |         2.841 |
| StressSurvey |      1.427 |        0.172 |   8.29 |   2.62e-06 |        1.052 |         1.802 |
| Time         |     -2.78  |        1.111 |  -2.5  |   0.0278   |       -5.201 |        -0.359 |
| const        |    nan     |        1.034 |   0.57 |   0.58     |      nan     |       nan     |

R-squared: 0.935</code></pre>
</div>
</div>
<p>The fitted model is</p>
<p><span class="math display">\[\widehat{Anxiety} = 0.589 + 1.427 \times StressSurvey - 2.780 \times Time,\]</span></p>
<p>with <span class="math inline">\(R^2 = 0.935\)</span>. If you read the output like a beginner, you might conclude: “Every extra survey point increases anxiety by 1.43, but every extra hour online <em>reduces</em> anxiety by 2.78.” Both coefficients look statistically convincing, yet both are wrong. The survey proxy is still curving away from the true stress measure, so the regression leans harder on StressSurvey and flips the Time sign to balance things out. We now have a high-<span class="math inline">\(R^2\)</span> model confidently proclaiming the opposite of the truth.</p>
</section>
<section id="question-6-multiple-regression-with-true-stress-and-time" class="level3">
<h3 class="anchored" data-anchor-id="question-6-multiple-regression-with-true-stress-and-time">Question 6: Multiple Regression with True Stress and Time</h3>
<div id="reg6-multiple-stress" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
Question 6: Multiple Regression - Anxiety ~ Stress + Time
======================================================================
|           |   Estimate |   Std. Error |             t |     p-value |   95% CI Low |   95% CI High |
|:----------|-----------:|-------------:|--------------:|------------:|-------------:|--------------:|
| Intercept |       -0   |          nan | nan           | nan         |         -0   |           0   |
| Stress    |        1   |            0 |   3.32219e+15 |   3.73e-181 |          1   |           1   |
| Time      |        0.1 |            0 |   4.71724e+13 |   5.55e-159 |          0.1 |           0.1 |
| const     |      nan   |            0 |  -1.62        |   0.13      |        nan   |         nan   |

R-squared: 1.000</code></pre>
</div>
</div>
<p>Substituting the actual stress measure lands exactly on the data-generating process:</p>
<p><span class="math display">\[\widehat{Anxiety} = 0.000 + 1.000 \times Stress + 0.100 \times Time,\]</span></p>
<p>with <span class="math inline">\(R^2 = 1.000\)</span>. Now the intercept is exactly zero (no stress, no time, no anxiety), each stress point adds one full point of anxiety, and each hour online adds the modest 0.1 bump we engineered. Perfect <span class="math inline">\(R^2\)</span> simply means the line passes through every observed point. Nothing about the sample changed—only the quality of the stress measurement. That small swap instantly restores trustworthy coefficients and a sensible story.</p>
</section>
<section id="question-7-model-comparison" class="level3">
<h3 class="anchored" data-anchor-id="question-7-model-comparison">Question 7: Model Comparison</h3>
<div id="reg7-comparison" class="cell" data-execution_count="10">
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
Question 7: Model Comparison
======================================================================

Model 1: Anxiety ~ StressSurvey + Time
----------------------------------------------------------------------
  R-squared: 0.9350
  Intercept: 0.5888
  StressSurvey coefficient: 1.4269
  Time coefficient: -2.7799

  Statistical Significance:
    Intercept p-value: 5.7954e-01
    StressSurvey p-value: 2.6158e-06
    Time p-value: 2.7816e-02

Model 2: Anxiety ~ Stress + Time
----------------------------------------------------------------------
  R-squared: 1.0000
  Intercept: -0.0000
  Stress coefficient: 1.0000
  Time coefficient: 0.1000

  Statistical Significance:
    Intercept p-value: 1.3014e-01
    Stress p-value: 3.7265e-181
    Time p-value: 5.5481e-159

======================================================================
Key Comparison Points:
======================================================================

1. R-squared:
   Proxy model: 0.9350
   True-stress model: 1.0000
   Absolute difference: 0.0650

2. Stress-related coefficient:
   Proxy coefficient: 1.4269 (42.7% off)
   True coefficient: 1.0000 (0.0% off)

3. Time coefficient:
   Proxy model: -2.7799 (-2879.9% off)
   True-stress model: 0.1000 (0.0% off)

4. Statistical significance:
   Both models clear the 5% threshold on every coefficient, despite only one set matching reality.</code></pre>
</div>
</div>
<div id="cell-fig-comparison" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div id="fig-comparison" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-comparison-output-1.png" width="1334" height="469" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Coefficient comparison between proxy-based and true-stress models
</figcaption>
</figure>
</div>
</div>
</div>
<p>To read the comparison, first notice that each model produces a headline number for fit (<span class="math inline">\(R^2\)</span>) and individual coefficients for Stress and Time. The charts echo the tables: bars closer to the green dashed lines tell the truth; bars that wander away are misleading.</p>
<p><em>R-squared:</em> Think of <span class="math inline">\(R^2\)</span> as the share of wiggle in Anxiety the model explains. The proxy model posts 0.935—almost indistinguishable from the perfect 1.000 of the true-stress model. If you judged models by this statistic alone, you would celebrate both.</p>
<p><em>Coefficients:</em> The real action lives here. The proxy model claims each survey point adds 1.427 anxiety points (43% too high) and each extra hour online <em>reduces</em> anxiety by 2.780. The true-stress model lands exactly on the known values of 1.000 and +0.100. In other words, small coefficient errors in the bar chart translate into entirely different policy stories.</p>
<p><em>Significance:</em> Both models report tiny p-values for every term. Statistical significance just says “this number is unlikely to be zero if the model were correct.” It does not guarantee the number is the <em>right</em> causal effect. That is why researchers must go beyond the asterisk column in regression tables.</p>
<div id="tbl-model-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="12">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-model-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2
</figcaption>
<div aria-describedby="tbl-model-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>| Model                                      |   Intercept | Stress/Proxy        | Time                |   R-squared |
|:-------------------------------------------|------------:|:--------------------|:--------------------|------------:|
| Anxiety ~ StressSurvey                     |      -1.524 | 1.047               |                     |       0.901 |
| Anxiety ~ Time                             |      -3.68  |                     | 5.340592227020359   |       0.563 |
| Anxiety ~ StressSurvey + Time              |       0.589 | 1.4269257460097156  | -2.779944482997918  |       0.935 |
| Anxiety ~ Stress + Time                    |      -0     | 1.0000000000000004  | 0.10000000000000198 |       1     |
| Subset (≤6): Anxiety ~ StressSurvey + Time |      -0     | 0.33333333333333365 | 0.09999999999999978 |       1     |</code></pre>
</div>
</div>
</figure>
</div>
<p><strong>Coefficient Accuracy vs.&nbsp;Fit:</strong> The proxy-based multiple regression boasts the second-highest <span class="math inline">\(R^2\)</span> yet supplies the most misleading coefficients. Even the subset model with perfect fit reports a StressSurvey slope of 0.333, which is “right” only because the survey scale is exactly three times the stress scale in that limited range. This table is a cheat sheet for beginners: always look at the meaning of the coefficients first, then decide whether the fit statistic is telling a coherent story.</p>
</section>
<section id="question-8-real-world-implications" class="level3">
<h3 class="anchored" data-anchor-id="question-8-real-world-implications">Question 8: Real-World Implications</h3>
<p><strong>Model 1 (StressSurvey + Time) – Headline:</strong> <em>“New Regression Finds Every Extra Hour of Social Media Cuts Anxiety by 2.8 Points.”</em><br>
Imagine a newsroom glancing only at the regression output: the Time coefficient is negative, the p-value is tiny, and the <span class="math inline">\(R^2\)</span> is strong. It takes discipline to dig deeper and realize the stress control is a bent survey proxy. Without that context, the story becomes “more scrolling, less anxiety.”</p>
<p><strong>Model 2 (Stress + Time) – Headline:</strong> <em>“Even at the Same Stress Level, More Social Media Raises Anxiety.”</em><br>
Here the data use the real stress measure, so the coefficient on Time is the modest +0.10 we expected. The same newsroom would now publish a cautionary tale about screen time harming mental health.</p>
<p>These competing headlines show how measurement choices—not statistical significance—drive public narratives. Parents primed to worry about social media will rally around Model 2; platform executives will amplify Model 1. Both sides can wave peer-reviewed regressions with impressive <span class="math inline">\(R^2\)</span> values, even though only one model reflects the causal truth.</p>
</section>
<section id="question-9-subset-analysis-and-graphical-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="question-9-subset-analysis-and-graphical-diagnostics">Question 9: Subset Analysis and Graphical Diagnostics</h3>
<div id="reg9-subset" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
Question 9: Subset Analysis to Avoid Misleading Significance
======================================================================

Strategy: analyze the lower-stress regime (StressSurvey ≤ 6) where the proxy is closest to linear.
  Original sample size: 15
  Subset sample size: 9
  Observations excluded: 6

Subset Regression Results:
----------------------------------------------------------------------
|              |   Estimate |   Std. Error |             t |    p-value |   95% CI Low |   95% CI High |
|:-------------|-----------:|-------------:|--------------:|-----------:|-------------:|--------------:|
| Intercept    |     -0     |          nan | nan           | nan        |       -0     |         0     |
| StressSurvey |      0.333 |            0 |   1.85585e+15 |   1.65e-90 |        0.333 |         0.333 |
| Time         |      0.1   |            0 |   1.42863e+14 |   7.94e-84 |        0.1   |         0.1   |
| const        |    nan     |            0 |  -1.28        |   0.249    |      nan     |       nan     |

R-squared: 1.000

True Relationship: Anxiety = Stress + 0.1 × Time
  Target coefficients: Intercept = 0.0, Stress = 1.0, Time = 0.1

Comparison with full proxy model:
----------------------------------------------------------------------
  Full-data StressSurvey coefficient: 1.4269
  Subset StressSurvey coefficient: 0.3333
  Full-data Time coefficient: -2.7799
  Subset Time coefficient: 0.1000
  Full-data R-squared: 0.9350
  Subset R-squared: 1.0000

Subset p-values:
  const: 2.4886e-01
  StressSurvey: 1.6521e-90
  Time: 7.9392e-84</code></pre>
</div>
</div>
<div id="cell-fig-subset-analysis" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div id="fig-subset-analysis" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-subset-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-subset-analysis-output-1.png" width="1334" height="566" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-subset-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Subset selection and coefficient comparison
</figcaption>
</figure>
</div>
</div>
</div>
<div id="cell-fig-graphical-diagnostics" class="cell" data-execution_count="15">
<div class="cell-output cell-output-display">
<div id="fig-graphical-diagnostics" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-graphical-diagnostics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-graphical-diagnostics-output-1.png" width="1334" height="950" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-graphical-diagnostics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Residual diagnostics: full proxy model vs subset model
</figcaption>
</figure>
</div>
</div>
</div>
<p>Focusing on <code>StressSurvey ≤ 6</code> yields</p>
<p><span class="math display">\[\widehat{Anxiety} = 0.000 + 0.333 \times StressSurvey + 0.100 \times Time,\]</span></p>
<p>with <span class="math inline">\(R^2 = 1.000\)</span>. In this calmer stress regime, the survey happens to track cortisol in a neat three-to-one ratio, so the regression adjusts the slope to 0.333 (one-third of the true coefficient) and recovers the correct +0.100 for Time. The residual panels translate the statistics into pictures: the full model’s residuals bend upward (a sign of non-linearity), while the subset residuals sit quietly around zero. The Q-Q plot likewise shows the subset residuals behaving normally. For beginners, this is the recipe: slice the data where your proxy behaves almost linearly, check the residuals, and only then trust the regression story.</p>
<p><strong>Takeaway:</strong> Segmenting the sample by stress severity and examining residual patterns surfaces hidden non-linearities. Rather than trusting the full-sample regression blindly, this approach pinpoints when measurement error will upend causal interpretation.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>